# Generated by Django 5.1.3 on 2024-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.TextField(db_index=True, default='test'),
            preserve_default=False,
        ),
    ]
