# Generated by Django 5.1.3 on 2024-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0001_initial'),
        ('hotels', '0001_initial'),
        ('reservation', '0002_rename_hotel_id_reservation_hotel_and_more'),
        ('users', '0002_alter_user_personal_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_in', 'check_out', 'user', 'hotel', 'room'], name='reservation_check_i_bcaf76_idx'),
        ),
    ]
