# Generated by Django 5.1.3 on 2024-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('user_name', models.TextField()),
                ('user_personal_id', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('nights', models.PositiveIntegerField()),
                ('hotel', models.UUIDField()),
                ('room_number', models.TextField()),
            ],
        ),
    ]
