# Generated by Django 5.1.3 on 2024-11-11 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
