# Generated by Django 5.1.3 on 2024-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0002_hotelrooms_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrooms',
            name='type',
            field=models.TextField(),
        ),
    ]
