# Generated by Django 5.1.3 on 2024-11-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0002_alter_hotelrooms_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelrooms',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
